export const templatesData = {
  categories: [
    "Product Reviews",
    "Service Feedback",
    "Employee Performance",
    "Customer Experience",
    "Educational Assessments",
    "Healthcare Feedback",
    "Technology Evaluation",
    "Creative Arts & Media",
    "Hospitality & Travel",
    "Professional Development",
  ],
  templates: [
    {
      name: "Consumer Electronics Detailed Review",
      description: "Comprehensive evaluation of electronic devices",
      category: "Product Reviews",
      status: "PROD",
      banner: "https://avatar.vercel.sh/electronics-review.jpg",
      fields: [
        { label: "Product Name", type: "input", order: 1 },
        { label: "Overall Quality", type: "star", order: 2 },
        { label: "Performance", type: "star", order: 3 },
        { label: "Value for Money", type: "star", order: 4 },
        { label: "Detailed Feedback", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Smartphone User Experience",
      description: "In-depth smartphone performance and satisfaction survey",
      category: "Product Reviews",
      status: "PROD",
      banner: "https://avatar.vercel.sh/smartphone-review.jpg",
      fields: [
        { label: "Phone Model", type: "input", order: 1 },
        { label: "Battery Performance", type: "star", order: 2 },
        { label: "Camera Quality", type: "star", order: 3 },
        { label: "User Interface", type: "star", order: 4 },
        { label: "Improvement Suggestions", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Restaurant Dining Experience",
      description: "Comprehensive restaurant service and food quality review",
      category: "Service Feedback",
      status: "PROD",
      banner: "https://avatar.vercel.sh/restaurant-review.jpg",
      fields: [
        { label: "Restaurant Name", type: "input", order: 1 },
        { label: "Food Quality", type: "star", order: 2 },
        { label: "Service Speed", type: "star", order: 3 },
        { label: "Staff Friendliness", type: "star", order: 4 },
        { label: "Additional Comments", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Customer Support Interaction",
      description: "Detailed evaluation of customer support experience",
      category: "Service Feedback",
      status: "PROD",
      banner: "https://avatar.vercel.sh/support-review.jpg",
      fields: [
        { label: "Support Channel", type: "input", order: 1 },
        { label: "Problem Resolution", type: "star", order: 2 },
        { label: "Representative Helpfulness", type: "star", order: 3 },
        { label: "Wait Time", type: "star", order: 4 },
        { label: "Specific Feedback", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Annual Employee Performance Review",
      description: "Comprehensive 360-degree employee evaluation",
      category: "Employee Performance",
      status: "PROD",
      banner: "https://avatar.vercel.sh/performance-review.jpg",
      fields: [
        { label: "Employee Name", type: "input", order: 1 },
        { label: "Professional Skills", type: "star", order: 2 },
        { label: "Teamwork", type: "star", order: 3 },
        { label: "Leadership Potential", type: "star", order: 4 },
        { label: "Development Recommendations", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Team Collaboration Assessment",
      description: "Evaluation of team dynamics and collaborative efforts",
      category: "Employee Performance",
      status: "PROD",
      banner: "https://avatar.vercel.sh/team-review.jpg",
      fields: [
        { label: "Team Name", type: "input", order: 1 },
        { label: "Communication", type: "star", order: 2 },
        { label: "Problem-Solving", type: "star", order: 3 },
        { label: "Mutual Support", type: "star", order: 4 },
        { label: "Improvement Areas", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Retail Shopping Experience",
      description: "Comprehensive customer journey in retail environment",
      category: "Customer Experience",
      status: "PROD",
      banner: "https://avatar.vercel.sh/retail-experience.jpg",
      fields: [
        { label: "Store Name", type: "input", order: 1 },
        { label: "Store Layout", type: "star", order: 2 },
        { label: "Staff Assistance", type: "star", order: 3 },
        { label: "Product Availability", type: "star", order: 4 },
        { label: "Detailed Feedback", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Online Platform User Experience",
      description: "Comprehensive evaluation of digital platform usability",
      category: "Customer Experience",
      status: "PROD",
      banner: "https://avatar.vercel.sh/platform-review.jpg",
      fields: [
        { label: "Platform Name", type: "input", order: 1 },
        { label: "User Interface", type: "star", order: 2 },
        { label: "Navigation", type: "star", order: 3 },
        { label: "Feature Satisfaction", type: "star", order: 4 },
        { label: "Improvement Suggestions", type: "textarea", order: 5 },
      ],
    },
    {
      name: "University Course Evaluation",
      description: "Comprehensive assessment of academic course quality",
      category: "Educational Assessments",
      status: "PROD",
      banner: "https://avatar.vercel.sh/course-review.jpg",
      fields: [
        { label: "Course Name", type: "input", order: 1 },
        { label: "Instructor Effectiveness", type: "star", order: 2 },
        { label: "Course Content", type: "star", order: 3 },
        { label: "Learning Experience", type: "star", order: 4 },
        { label: "Detailed Feedback", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Online Learning Platform Review",
      description: "Evaluation of digital learning experience",
      category: "Educational Assessments",
      status: "PROD",
      banner: "https://avatar.vercel.sh/online-learning-review.jpg",
      fields: [
        { label: "Platform Name", type: "input", order: 1 },
        { label: "Course Variety", type: "star", order: 2 },
        { label: "Learning Interface", type: "star", order: 3 },
        { label: "Instructor Quality", type: "star", order: 4 },
        { label: "Improvement Areas", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Hospital Patient Experience",
      description: "Comprehensive healthcare service evaluation",
      category: "Healthcare Feedback",
      status: "PROD",
      banner: "https://avatar.vercel.sh/hospital-review.jpg",
      fields: [
        { label: "Department", type: "input", order: 1 },
        { label: "Doctor Communication", type: "star", order: 2 },
        { label: "Treatment Quality", type: "star", order: 3 },
        { label: "Facility Cleanliness", type: "star", order: 4 },
        { label: "Additional Comments", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Telemedicine Service Review",
      description: "Evaluation of remote healthcare consultation",
      category: "Healthcare Feedback",
      status: "PROD",
      banner: "https://avatar.vercel.sh/telemedicine-review.jpg",
      fields: [
        { label: "Service Provider", type: "input", order: 1 },
        { label: "Consultation Quality", type: "star", order: 2 },
        { label: "Technical Experience", type: "star", order: 3 },
        { label: "Doctor Accessibility", type: "star", order: 4 },
        { label: "Improvement Suggestions", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Software Product Evaluation",
      description: "Comprehensive software performance and usability review",
      category: "Technology Evaluation",
      status: "PROD",
      banner: "https://avatar.vercel.sh/software-review.jpg",
      fields: [
        { label: "Software Name", type: "input", order: 1 },
        { label: "Functionality", type: "star", order: 2 },
        { label: "User Interface", type: "star", order: 3 },
        { label: "Performance Speed", type: "star", order: 4 },
        { label: "Detailed Feedback", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Cloud Service Review",
      description: "Evaluation of cloud computing platform",
      category: "Technology Evaluation",
      status: "PROD",
      banner: "https://avatar.vercel.sh/cloud-review.jpg",
      fields: [
        { label: "Service Provider", type: "input", order: 1 },
        { label: "Reliability", type: "star", order: 2 },
        { label: "Performance", type: "star", order: 3 },
        { label: "Customer Support", type: "star", order: 4 },
        { label: "Improvement Areas", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Film and Media Review",
      description: "Comprehensive movie or media content evaluation",
      category: "Creative Arts & Media",
      status: "PROD",
      banner: "https://avatar.vercel.sh/film-review.jpg",
      fields: [
        { label: "Title", type: "input", order: 1 },
        { label: "Storytelling", type: "star", order: 2 },
        { label: "Acting Performance", type: "star", order: 3 },
        { label: "Technical Quality", type: "star", order: 4 },
        { label: "In-Depth Review", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Music Album Critique",
      description: "Comprehensive musical album evaluation",
      category: "Creative Arts & Media",
      status: "PROD",
      banner: "https://avatar.vercel.sh/music-review.jpg",
      fields: [
        { label: "Album Name", type: "input", order: 1 },
        { label: "Musical Composition", type: "star", order: 2 },
        { label: "Vocal Performance", type: "star", order: 3 },
        { label: "Production Quality", type: "star", order: 4 },
        { label: "Detailed Critique", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Hotel Stay Experience",
      description: "Comprehensive hotel accommodation review",
      category: "Hospitality & Travel",
      status: "PROD",
      banner: "https://avatar.vercel.sh/hotel-review.jpg",
      fields: [
        { label: "Hotel Name", type: "input", order: 1 },
        { label: "Room Quality", type: "star", order: 2 },
        { label: "Staff Service", type: "star", order: 3 },
        { label: "Amenities", type: "star", order: 4 },
        { label: "Additional Comments", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Travel Experience Review",
      description: "Comprehensive travel and tour evaluation",
      category: "Hospitality & Travel",
      status: "PROD",
      banner: "https://avatar.vercel.sh/travel-review.jpg",
      fields: [
        { label: "Destination", type: "input", order: 1 },
        { label: "Accommodation", type: "star", order: 2 },
        { label: "Local Experience", type: "star", order: 3 },
        { label: "Overall Satisfaction", type: "star", order: 4 },
        { label: "Detailed Feedback", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Professional Training Program",
      description: "Evaluation of professional development course",
      category: "Professional Development",
      status: "PROD",
      banner: "https://avatar.vercel.sh/training-review.jpg",
      fields: [
        { label: "Program Name", type: "input", order: 1 },
        { label: "Content Relevance", type: "star", order: 2 },
        { label: "Instructor Quality", type: "star", order: 3 },
        { label: "Practical Applicability", type: "star", order: 4 },
        { label: "Improvement Suggestions", type: "textarea", order: 5 },
      ],
    },
    {
      name: "Mentorship Program Assessment",
      description: "Comprehensive evaluation of mentorship experience",
      category: "Professional Development",
      status: "PROD",
      banner: "https://avatar.vercel.sh/mentorship-review.jpg",
      fields: [
        { label: "Program Name", type: "input", order: 1 },
        { label: "Mentor Guidance", type: "star", order: 2 },
        { label: "Learning Outcomes", type: "star", order: 3 },
        { label: "Personal Growth", type: "star", order: 4 },
        { label: "Detailed Feedback", type: "textarea", order: 5 },
      ],
    },
  ],
};
